services:
  db:
    container_name: ligoj-db
    restart: always
    networks:
      - ligoj-network
  api:
    container_name: ligoj-api
    image: ${LIGOJ_REGISTRY:-}ligoj/ligoj-api:${LIGOJ_VERSION:-3.3.0}
    build:
      context: app-api
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    restart: always
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: ${LIGOJ_API_PORT:-8081}
      CUSTOM_OPTS: "-Djdbc.host=ligoj-db"
      CRYPTO: "-Dapp.crypto.password=public"
    links:
      - db:ligoj-db
    depends_on: 
      - db
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
  ui:
    container_name: ligoj-ui
    image: ${LIGOJ_REGISTRY:-}ligoj/ligoj-ui:${LIGOJ_VERSION:-3.3.0}
    build:
      context: app-ui
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    restart: always
    environment:
      JAVA_OPTIONS: "-Dsecurity=Rest"
      SERVER_PORT: ${LIGOJ_WEB_PORT:-8080}
      CUSTOM_OPTS: ""
    links:
      - api:ligoj-api
    ports: 
      - "${LIGOJ_PORT:-8080}:${LIGOJ_WEB_PORT:-8080}"
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
networks:
  ligoj-network:
