services:
  db:
    container_name: ligoj-db
    image: postgres:15.3-bookworm
    environment:
      POSTGRES_DB: ligoj
      POSTGRES_USER: ligoj
      POSTGRES_PASSWORD: ligoj
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}/postgres:/var/lib/postgresql/data
  api:
    container_name: ligoj-api
    environment:
      CUSTOM_OPTS: ${LIGOJ_API_CUSTOM_OPTS:--Djdbc.host=ligoj-db -Djdbc.vendor=postgresql -Djdbc.port=5432 -Djpa.dialect=org.ligoj.bootstrap.core.dao.PostgreSQL95NoSchemaDialect -Djdbc.driverClassName=org.postgresql.Driver -Dcom.sun.jndi.ldap.connect.pool.initsize=1 -Dcom.sun.jndi.ldap.connect.pool.maxsize=1 -Dcom.sun.jndi.ldap.connect.pool.prefsize=1 -Dcom.sun.jndi.ldap.connect.pool.debug=all}
