services:
  db:
    container_name: ligoj-db
    restart: always
    networks:
      - ligoj-network
  api:
    container_name: ligoj-api
    image: ${LIGOJ_REGISTRY:-}ligoj/ligoj-api:${LIGOJ_VERSION:-3.3.0}
    build:
      context: app-api
      args:
        BUILDPLATFORM: ${LIGOJ_BUILD_PLATFORM:-linux/amd64}
        TARGETPLATFORM: ${LIGOJ_TARGET_PLATFORM:-linux/amd64}
        JAVA_VERSION: ${JAVA_VERSION:-21-jdk"}
        MAVEN_VERSION: ${MAVEN_VERSION:-3.9.5-amazoncorretto-21-debian-bookworm}
    restart: always
    environment:
      JAVA_OPTIONS: ${LIGOJ_API_JAVA_OPTIONS:--Duser.timezone=UTC}
      CUSTOM_OPTS: ${LIGOJ_API_CUSTOM_OPTS:--Djdbc.host=ligoj-db}
      CRYPTO: ${LIGOJ_API_CRYPTO:--Dapp.crypto.password=public}
      PREPARE_RUN: ${LIGOJ_API_PREPARE_RUN:-echo "No PREPARE_RUN"}
    links:
      - db:ligoj-db
    depends_on:
      - db
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
  ui:
    container_name: ligoj-ui
    image: ${LIGOJ_REGISTRY:-}ligoj/ligoj-ui:${LIGOJ_VERSION:-3.3.0}
    build:
      context: app-ui
      args:
        BUILDPLATFORM: ${LIGOJ_BUILD_PLATFORM:-linux/amd64}
        TARGETPLATFORM: ${LIGOJ_TARGET_PLATFORM:-linux/amd64}
        JAVA_VERSION: ${JAVA_VERSION:-21-jdk"}
        NODE_VERSION: ${NODE_VERSION:-16.20-bookworm-slim"}
        MAVEN_VERSION: ${MAVEN_VERSION:-3.9.5-amazoncorretto-21-debian-bookworm}
    restart: always
    environment:
      SERVER_PORT: ${LIGOJ_WEB_PORT:-8080}
      CONTEXT_URL: ${LIGOJ_WEB_CONTEXT_URL:-/ligoj}
      JAVA_OPTIONS: ${LIGOJ_WEB_JAVA_OPTIONS:--Duser.timezone=UTC -Dsecurity=Rest}"
      CUSTOM_OPTS: ${LIGOJ_WEB_CUSTOM_OPTS:-}
      CRYPTO: ${LIGOJ_WEB_CRYPTO:--Dapp.crypto.password=public}
      PREPARE_RUN: ${LIGOJ_WEB_PREPARE_RUN:-echo "No PREPARE_RUN"}
    links:
      - api:ligoj-api
    ports:
      - "${LIGOJ_PORT:-8080}:${LIGOJ_WEB_PORT:-8080}"
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
networks:
  ligoj-network:
