version: '3.8'
services:
  db:
    container_name: ligoj-db
    restart: always
    networks:
      - ligoj-network
  api:
    container_name: ligoj-api
    image: ligoj/ligoj-api:3.3.0
    restart: always
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8081"
      CUSTOM_OPTS: "-Djdbc.host=ligoj-db"
      CRYPTO: "-Dapp.crypto.password=public"
    links:
      - db:ligoj-db
    depends_on: 
      - db
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
  ui:
    container_name: ligoj-ui
    image: ligoj/ligoj-ui:3.3.0
    restart: always
    environment:
      JAVA_OPTIONS: "-Dsecurity=Rest"
      SERVER_PORT: "8080"
      CUSTOM_OPTS: ""
    links:
      - api:ligoj-api
    ports: 
      - "8080:8080"
    volumes:
      - ${LIGOJ_HOME:-/home/ligoj}:/home/ligoj
    networks:
      - ligoj-network
networks:
  ligoj-network:
