FROM openjdk:8-jre
LABEL maintainer "fabrice.daugan@gmail.com,alocquet@gmail.com"

RUN set -xe \
  apt-get update && \
  apt-get update --fix-missing && \
  apt-get install -y \
   curl \
   mysql-client

ARG APP="ligoj"
ARG GROUP_ID="org.${APP}.app"
ARG ARTIFACT_ID="app-api"
ARG NEXUS_HOST="oss.sonatype.org"
ARG NEXUS_URL="https://${NEXUS_HOST}"
ARG VERSION
#ARG WAR_URL="${NEXUS_URL}/service/local/repositories/orgligoj-1087/content/org/${APP}/app/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.war"
ARG WAR_URL="${NEXUS_URL}/service/local/artifact/maven/redirect?r=public&g=${GROUP_ID}&a=${ARTIFACT_ID}&v=${VERSION}&p=war"
ENV CONTEXT "${APP}-api"
ENV CONTEXT_URL "/${CONTEXT}"
ENV SERVER_HOST "0.0.0.0"
ENV SERVER_PORT "8081"
ENV LIGOJ_HOME /home/ligoj
ENV SERVER_HOME /usr/local/ligoj
ENV JAVA_MEMORY="-Xms712M -Xmx1024M"
ENV CUSTOM_OPTS="-Djpa.hbm2ddl=update"
ENV CRYPTO="-Dapp.crypto.password=public"
ENV JAVA_OPTIONS="-Duser.timezone=UTC"
RUN set -xe && \
  mkdir -p "$SERVER_HOME" && \
  mkdir -p "$LIGOJ_HOME" && \
    echo "Downloading application ${WAR_URL}" && \
        curl -sSL "${WAR_URL}" -o "${SERVER_HOME}/ligoj-api.war" && \
  echo "Cleaning" && \
        apt-get purge -y --auto-remove curl

WORKDIR "${LIGOJ_HOME}"

# Without database container
CMD java $JAVA_MEMORY $JAVA_OPTIONS $CRYPTO $CUSTOM_OPTS -Dserver.address="${SERVER_HOST}" -Dserver.port="${SERVER_PORT}" -Dserver.context-path="${CONTEXT_URL}" -Dligoj.home="${LIGOJ_HOME}" -jar "$SERVER_HOME/ligoj-api.war"
HEALTHCHECK --interval=5s --timeout=3s --retries=10 \
CMD curl -v --silent "http://localhost:${SERVER_PORT}${CONTEXT_URL}/manage/health" 2>&1 | grep UP