# Licensed under MIT (https://github.com/ligoj/ligoj/blob/master/LICENSE)
# Properties (not JSON/XML) on purpose:
# - JsonConfigurationFactory needs Jackson 2 (com.fasterxml.*), removed by the Jackson 3 migration.
# - XmlConfigurationFactory uses the JDK DOM parser, which triggers a LinkageError when Log4j
#   initializes inside Spring's SimpleThrowawayClassLoader (the JPA temp classloader hands
#   Hibernate our ResourceScanner, whose static logger boots a fresh Log4j in that child-first
#   loader; it re-defines org.xml.sax.* from the jrt image — not in OverridingClassLoader's
#   excluded packages — clashing with java.xml's DocumentBuilder signature).
# The properties factory is parsed by Log4j itself with no external dependency.
status = warn
name = Main
monitorInterval = 60

property.filename = ${env:LIGOJ_HOME:-${sys:ligoj.home:-target}}/${sys:ligoj.log.file.name:-api-rolling.log}

filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%principal] %msg%xEx{filters(com.sun.proxy,jdk.proxy3,org.springframework.data.projection,org.springframework.dao.support,org.springframework.transaction,java.lang.Thread,org.apache.cxf,org.eclipse.jetty,org.springframework.web,javax.servlet,org.springframework.aop,org.junit,org.apache.maven,sun.reflect,java.lang.reflect,org.springframework.cglib,org.springframework.security,org.springframework.boot.actuate,jdk.internal.reflect,org.springframework.cache.jcache.interceptor,java.util.stream,org.springframework.data.repository.core.support,org.springframework.data.jpa.repository.support,java.util.Iterator.forEachRemaining,java.util.Spliterators$IteratorSpliterator,java.util.concurrent.ForkJoin,java.util.concurrent.CountedCompleter,org.springframework.cache.interceptor.Cache)}%n

appender.verbose.type = Console
appender.verbose.name = STDOUT_VERBOSE
appender.verbose.layout.type = PatternLayout
appender.verbose.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level [%principal] %logger{36} - %msg%n

# Routing: an actual rolling file when ligoj.log.file.enabled (default), else a Null sink.
appender.routing.type = Routing
appender.routing.name = MaybeRolling
appender.routing.routes.type = Routes
appender.routing.routes.pattern = ${sys:ligoj.log.file.enabled:-true}
appender.routing.routes.file.type = Route
appender.routing.routes.file.key = true
appender.routing.routes.file.app.type = RollingFile
appender.routing.routes.file.app.name = RollingFileActive
appender.routing.routes.file.app.fileName = ${filename}
appender.routing.routes.file.app.filePattern = ${filename}.%i.gz
appender.routing.routes.file.app.layout.type = PatternLayout
appender.routing.routes.file.app.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level [%principal] %logger{36} - %msg%n
appender.routing.routes.file.app.policies.type = Policies
appender.routing.routes.file.app.policies.size.type = SizeBasedTriggeringPolicy
appender.routing.routes.file.app.policies.size.size = ${sys:ligoj.log.file.size:-10 MB}
appender.routing.routes.nofile.type = Route
appender.routing.routes.nofile.key = false
appender.routing.routes.nofile.app.type = Null
appender.routing.routes.nofile.app.name = NoFile

rootLogger.level = ${sys:log.level:-info}
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.rolling.ref = MaybeRolling
