apiVersion: v1
kind: Service
metadata:
  name: {{ include "ligoj.fullname" . }}-api
  labels:
    {{- include "ligoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    {{- include "ligoj.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ligoj.fullname" . }}-ui
  labels:
    {{- include "ligoj.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      {{- if and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ligoj.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
